import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowLeft, Package } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getProductEditorRecord } from "@/lib/admin/product-data";
export default async function ProductPreviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ locale?: string }> }) { const { id } = await params; const { locale = "th" } = await searchParams; if (!/^\d+$/.test(id) || !["th", "en"].includes(locale)) notFound(); const product = await getProductEditorRecord(Number(id)); if (!product) notFound(); const name = locale === "en" ? product.nameEn : product.nameTh; const description = locale === "en" ? product.descriptionEn : product.descriptionTh; return <div className="mx-auto max-w-6xl space-y-6"><div className="flex justify-between gap-4"><div><Badge variant="secondary">Preview · {product.published ? "เผยแพร่" : "ฉบับร่าง"}</Badge><h1 className="mt-3 font-headline-lg font-semibold">ตัวอย่างสินค้า</h1></div><Button asChild variant="outline"><Link href={`/admin/products/${product.id}`}><ArrowLeft className="size-4" />กลับไปแก้ไข</Link></Button></div><Card><CardContent className="grid gap-8 p-6 md:grid-cols-2 md:p-10"><div className="relative aspect-square overflow-hidden rounded-lg bg-muted">{product.coverImage ? <Image src={product.coverImage} alt={name} fill className="object-cover" sizes="50vw" /> : <Package className="absolute left-1/2 top-1/2 size-20 -translate-x-1/2 -translate-y-1/2 text-muted-foreground" />}</div><div><p className="font-label-md text-primary">{product.sku}</p><h2 className="mt-2 font-display-md font-semibold">{name}</h2>{product.basePrice !== null ? <p className="mt-4 font-headline-md text-primary">{product.basePrice.toLocaleString(locale === "en" ? "en-US" : "th-TH", { style: "currency", currency: product.currency })}</p> : null}<p className="mt-6 whitespace-pre-line font-body-md text-muted-foreground">{description}</p><div className="mt-6 flex flex-wrap gap-2">{product.variants.map((variant, index) => <Badge key={`${variant.sku}-${variant.attributeValueIds.join("-")}`} variant={variant.isDefault ? "default" : "outline"}>{variant.sku || `Variant ${index + 1}`} · {variant.price.toLocaleString()}</Badge>)}</div></div></CardContent></Card></div>; }
