"use client";

import Link from "next/link";
import { useActionState, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, ImagePlus, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { saveProductAction } from "@/app/admin/(panel)/products/actions";
import { AdminSelect } from "@/components/admin/admin-select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { slugifyAdminTitle, type ActionResult } from "@/lib/admin/validation";

type CategoryOption = { id: number; nameTh: string; nameEn: string; subCategories: { id: number; nameTh: string }[]; attributes: { id: number; nameTh: string; isRequired: boolean; values: { id: number; valueTh: string; valueEn: string; colorHex: string | null }[] }[] };
type ProductRecord = { id: number; updatedAt: Date; slug: string; sku: string; nameTh: string; nameEn: string; descriptionTh: string | null; descriptionEn: string | null; usageGuideTh: string | null; usageGuideEn: string | null; coverImage: string | null; catalogPdf: string | null; basePrice: number | null; currency: string; featured: boolean; published: boolean; sortOrder: number; categoryId: number | null; subCategoryId: number | null; brandId: number | null; unitId: number | null; pricingUnitId: number | null; images: ImageRow[]; attributeValueIds: number[]; variants: VariantRow[] };
type ImageRow = { _key?: string; url: string; altTh: string; altEn: string; sortOrder: number };
type VariantRow = { _key?: string; sku: string; price: number; comparePrice: number | ""; image: string; isAvailable: boolean; isDefault: boolean; sortOrder: number; attributeValueIds: number[] };
type Option = { id: number; name?: string; nameTh?: string };
const initialState: ActionResult = { success: false, message: "" };

export function ProductForm({ record, options }: { record: ProductRecord | null; options: { categories: CategoryOption[]; brands: Option[]; units: Option[]; pricingUnits: Option[] } }) {
  const router = useRouter(); const [state, action, pending] = useActionState(saveProductAction, initialState); const dirtyRef = useRef(false);
  const [categoryId, setCategoryId] = useState(record?.categoryId ? String(record.categoryId) : "none"); const category = options.categories.find((item) => item.id === Number(categoryId));
  const [titleEn, setTitleEn] = useState(record?.nameEn || ""); const [slug, setSlug] = useState(record?.slug || "");
  const [images, setImages] = useState<ImageRow[]>(() => (record?.images || []).map((image, index) => ({ ...image, _key: `image-${index}-${image.url}` }))); const [variants, setVariants] = useState<VariantRow[]>(() => (record?.variants || []).map((variant, index) => ({ ...variant, _key: `variant-${index}-${variant.sku}` }))); const [attributeValueIds, setAttributeValueIds] = useState<number[]>(record?.attributeValueIds || []);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirtyRef.current) event.preventDefault(); }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, []);
  useEffect(() => { if (state.success) { dirtyRef.current = false; toast.success(state.message); router.push("/admin/products"); router.refresh(); } else if (state.message) toast.error(state.message); }, [state, router]);
  const updateVariant = (index: number, patch: Partial<VariantRow>) => { dirtyRef.current = true; setVariants((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row)); };
  const toggleValue = (id: number) => { dirtyRef.current = true; setAttributeValueIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); };
  const optionLabel = (option: Option) => option.name || option.nameTh || String(option.id);
  return <form action={action} onChange={() => { dirtyRef.current = true; }} className="space-y-6">
    <input type="hidden" name="id" value={record?.id || ""} /><input type="hidden" name="updatedAt" value={record?.updatedAt ? new Date(record.updatedAt).toISOString() : ""} /><input type="hidden" name="imagesJson" value={JSON.stringify(images)} readOnly /><input type="hidden" name="variantsJson" value={JSON.stringify(variants)} readOnly /><input type="hidden" name="attributeValueIdsJson" value={JSON.stringify(attributeValueIds)} readOnly />
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="font-headline-lg font-semibold">{record ? "แก้ไขสินค้า" : "เพิ่มสินค้า"}</h1><p className="font-body-sm text-muted-foreground">จัดการข้อมูล รูปภาพ คุณลักษณะ และ variants ใน transaction เดียว</p></div><div className="flex flex-wrap gap-2">{record ? <Button asChild variant="outline"><Link href={`/admin/preview/products/${record.id}`} target="_blank"><Eye className="size-4" />Preview</Link></Button> : null}<Button type="submit" name="intent" value="draft" variant="outline" disabled={pending}><Save className="size-4" />บันทึกร่าง</Button><Button type="submit" name="intent" value="publish" disabled={pending}>เผยแพร่</Button></div></div>
    {state.conflict ? <p className="rounded-md border border-destructive bg-error-container p-3 font-body-sm text-on-error-container">{state.message}</p> : null}
    <Tabs defaultValue="general" className="space-y-4"><TabsList className="h-auto flex-wrap"><TabsTrigger value="general" className="font-label-md">ข้อมูลหลัก</TabsTrigger><TabsTrigger value="classification" className="font-label-md">หมวดและคุณลักษณะ</TabsTrigger><TabsTrigger value="media" className="font-label-md">รูปและเอกสาร</TabsTrigger><TabsTrigger value="variants" className="font-label-md">Variants ({variants.length})</TabsTrigger></TabsList>
      <TabsContent value="general"><div className="grid gap-6 xl:grid-cols-[1fr_320px]"><Card><CardHeader><CardTitle className="font-headline-sm">ชื่อและรายละเอียด</CardTitle></CardHeader><CardContent><Tabs defaultValue="th"><TabsList><TabsTrigger value="th" className="font-label-md">ไทย</TabsTrigger><TabsTrigger value="en" className="font-label-md">English</TabsTrigger></TabsList><TabsContent value="th" className="mt-5 space-y-4"><div className="space-y-2"><Label className="font-label-md">ชื่อสินค้า</Label><Input name="nameTh" defaultValue={record?.nameTh} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">คำอธิบาย</Label><Textarea name="descriptionTh" defaultValue={record?.descriptionTh || ""} rows={6} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">คำแนะนำการใช้งาน</Label><Textarea name="usageGuideTh" defaultValue={record?.usageGuideTh || ""} rows={4} className="font-body-sm" /></div></TabsContent><TabsContent value="en" className="mt-5 space-y-4"><div className="space-y-2"><Label className="font-label-md">Product name</Label><Input name="nameEn" value={titleEn} onChange={(event) => setTitleEn(event.target.value)} onBlur={() => { if (!slug) setSlug(slugifyAdminTitle(titleEn)); }} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">Description</Label><Textarea name="descriptionEn" defaultValue={record?.descriptionEn || ""} rows={6} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">Usage guide</Label><Textarea name="usageGuideEn" defaultValue={record?.usageGuideEn || ""} rows={4} className="font-body-sm" /></div></TabsContent></Tabs></CardContent></Card><Card><CardHeader><CardTitle className="font-headline-sm">รหัสและราคา</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label className="font-label-md">Slug</Label><Input name="slug" value={slug} onChange={(event) => setSlug(event.target.value)} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">SKU หลัก</Label><Input name="sku" defaultValue={record?.sku} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">ราคาฐาน</Label><Input name="basePrice" type="number" min="0" step="0.01" defaultValue={record?.basePrice ?? ""} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">สกุลเงิน</Label><Input name="currency" defaultValue={record?.currency || "THB"} className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">ลำดับ</Label><Input name="sortOrder" type="number" defaultValue={record?.sortOrder || 0} className="font-body-sm" /></div><label className="flex items-center gap-2 font-label-md"><input name="featured" type="checkbox" defaultChecked={record?.featured} />สินค้าแนะนำ</label></CardContent></Card></div></TabsContent>
      <TabsContent value="classification"><Card><CardHeader><CardTitle className="font-headline-sm">การจัดหมวดหมู่</CardTitle></CardHeader><CardContent className="space-y-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><SelectField name="categoryId" label="หมวดหมู่" value={categoryId} onChange={setCategoryId} options={options.categories.map((item) => ({ id: item.id, label: item.nameTh }))} /><SelectField name="subCategoryId" label="หมวดหมู่ย่อย" defaultValue={record?.subCategoryId} options={(category?.subCategories || []).map((item) => ({ id: item.id, label: item.nameTh }))} /><SelectField name="brandId" label="แบรนด์" defaultValue={record?.brandId} options={options.brands.map((item) => ({ id: item.id, label: optionLabel(item) }))} /><SelectField name="unitId" label="หน่วยสินค้า" defaultValue={record?.unitId} options={options.units.map((item) => ({ id: item.id, label: optionLabel(item) }))} /><SelectField name="pricingUnitId" label="หน่วยราคา" defaultValue={record?.pricingUnitId} options={options.pricingUnits.map((item) => ({ id: item.id, label: optionLabel(item) }))} /></div><div className="space-y-5">{category?.attributes.map((attribute) => <div key={attribute.id}><p className="font-label-md font-semibold">{attribute.nameTh}{attribute.isRequired ? " *" : ""}</p><div className="mt-2 flex flex-wrap gap-2">{attribute.values.map((value) => <label key={value.id} className="flex items-center gap-2 rounded-md border bg-background px-3 py-2 font-label-sm"><input type="checkbox" checked={attributeValueIds.includes(value.id)} onChange={() => toggleValue(value.id)} />{value.colorHex ? <span className="size-4 rounded-full border" style={{ backgroundColor: value.colorHex }} /> : null}{value.valueTh} / {value.valueEn}</label>)}</div></div>)}{!category ? <p className="font-body-sm text-muted-foreground">เลือกหมวดหมู่เพื่อกำหนดคุณลักษณะ</p> : null}</div></CardContent></Card></TabsContent>
      <TabsContent value="media"><Card><CardHeader><CardTitle className="font-headline-sm">รูปภาพและแคตตาล็อก</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label className="font-label-md">รูปปก</Label><Input name="coverImage" defaultValue={record?.coverImage || ""} placeholder="/api/uploads/..." className="font-body-sm" /></div><div className="space-y-2"><Label className="font-label-md">Catalog PDF</Label><Input name="catalogPdf" defaultValue={record?.catalogPdf || ""} placeholder="/api/uploads/..." className="font-body-sm" /></div></div><div className="flex items-center justify-between"><h3 className="font-headline-sm">รูปเพิ่มเติม</h3><Button type="button" variant="outline" onClick={() => setImages((current) => [...current, { _key: crypto.randomUUID(), url: "", altTh: "", altEn: "", sortOrder: current.length }])}><ImagePlus className="size-4" />เพิ่มรูป</Button></div>{images.map((image, index) => <div key={image._key} className="grid gap-3 rounded-md border p-4 md:grid-cols-[1fr_1fr_1fr_auto]"><Input value={image.url} onChange={(event) => setImages((current) => current.map((row, i) => i === index ? { ...row, url: event.target.value } : row))} placeholder="URL รูป" className="font-body-sm" /><Input value={image.altTh} onChange={(event) => setImages((current) => current.map((row, i) => i === index ? { ...row, altTh: event.target.value } : row))} placeholder="Alt ภาษาไทย" className="font-body-sm" /><Input value={image.altEn} onChange={(event) => setImages((current) => current.map((row, i) => i === index ? { ...row, altEn: event.target.value } : row))} placeholder="English alt" className="font-body-sm" /><Button type="button" variant="ghost" size="icon" onClick={() => setImages((current) => current.filter((_, i) => i !== index))}><Trash2 className="size-4 text-destructive" /></Button></div>)}<Button asChild type="button" variant="link"><Link href="/admin/media" target="_blank">เปิดคลังไฟล์</Link></Button></CardContent></Card></TabsContent>
      <TabsContent value="variants"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="font-headline-sm">ตัวเลือกสินค้า</CardTitle><Button type="button" variant="outline" onClick={() => setVariants((current) => [...current, { _key: crypto.randomUUID(), sku: "", price: 0, comparePrice: "", image: "", isAvailable: true, isDefault: current.length === 0, sortOrder: current.length, attributeValueIds: [] }])}><Plus className="size-4" />เพิ่ม Variant</Button></div></CardHeader><CardContent className="space-y-4">{variants.map((variant, index) => <div key={variant._key} className="space-y-4 rounded-md border p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Input value={variant.sku} onChange={(event) => updateVariant(index, { sku: event.target.value })} placeholder="SKU" className="font-body-sm" /><Input type="number" min="0" step="0.01" value={variant.price} onChange={(event) => updateVariant(index, { price: Number(event.target.value) })} placeholder="ราคา" className="font-body-sm" /><Input type="number" min="0" step="0.01" value={variant.comparePrice} onChange={(event) => updateVariant(index, { comparePrice: event.target.value === "" ? "" : Number(event.target.value) })} placeholder="ราคาเปรียบเทียบ" className="font-body-sm" /><Input value={variant.image} onChange={(event) => updateVariant(index, { image: event.target.value })} placeholder="URL รูป" className="font-body-sm" /><Button type="button" variant="ghost" onClick={() => setVariants((current) => current.filter((_, i) => i !== index))}><Trash2 className="size-4 text-destructive" />ลบ</Button></div><div className="flex flex-wrap gap-4"><label className="flex items-center gap-2 font-label-sm"><input type="checkbox" checked={variant.isAvailable} onChange={(event) => updateVariant(index, { isAvailable: event.target.checked })} />เปิดให้เลือก</label><label className="flex items-center gap-2 font-label-sm"><input type="checkbox" checked={variant.isDefault} onChange={(event) => { setVariants((current) => current.map((row, i) => ({ ...row, isDefault: i === index ? event.target.checked : false }))); }} />ค่าเริ่มต้น</label></div><div><p className="font-label-md font-semibold">ชุดคุณลักษณะ</p><div className="mt-2 flex flex-wrap gap-2">{category?.attributes.flatMap((attribute) => attribute.values).map((value) => <label key={value.id} className="flex items-center gap-2 rounded-md border px-3 py-2 font-label-sm"><input type="checkbox" checked={variant.attributeValueIds.includes(value.id)} onChange={() => updateVariant(index, { attributeValueIds: variant.attributeValueIds.includes(value.id) ? variant.attributeValueIds.filter((id) => id !== value.id) : [...variant.attributeValueIds, value.id] })} />{value.valueTh}</label>)}</div></div></div>)}{!variants.length ? <p className="py-10 text-center font-body-sm text-muted-foreground">ยังไม่มี Variant สินค้ายังสามารถใช้ราคาฐานได้</p> : null}</CardContent></Card></TabsContent>
    </Tabs>
  </form>;
}

function SelectField({ name, label, options, defaultValue, value, onChange }: { name: string; label: string; options: { id: number; label: string }[]; defaultValue?: number | null; value?: string; onChange?: (value: string) => void }) {
  return <div className="space-y-2"><Label htmlFor={name} className="font-label-md">{label}</Label><AdminSelect name={name} value={value} defaultValue={value === undefined ? defaultValue ? String(defaultValue) : "none" : undefined} onValueChange={onChange} className="w-full font-body-sm" options={[{ value: "none", label: "ไม่ระบุ" }, ...options.map((option) => ({ value: String(option.id), label: option.label }))]} /></div>;
}
