import { NextRequest, NextResponse } from "next/server";
import { resolveUploadPath } from "@/lib/admin/security";
import { openFile } from "@/lib/file-stream";
import { getPrisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const TOKEN_PATTERN = /^[a-f0-9]{64}$/i;
const MIME_TYPES = new Set([
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
]);

export async function GET(
  _request: NextRequest,
  props: { params: Promise<{ token: string }> },
) {
  const { token } = await props.params;
  if (!TOKEN_PATTERN.test(token)) {
    return new NextResponse("Not Found", { status: 404 });
  }

  let attachment;
  try {
    attachment = await getPrisma().quotationRequest.findUnique({
      where: { boqDownloadToken: token.toLowerCase() },
      select: {
        boqStoragePath: true,
        boqOriginalName: true,
        boqMimeType: true,
        boqSize: true,
      },
    });
  } catch (error) {
    console.error("Quotation attachment lookup failed:", error);
    return new NextResponse("Internal Server Error", { status: 500 });
  }

  if (
    !attachment?.boqStoragePath ||
    !attachment.boqOriginalName ||
    !attachment.boqMimeType ||
    attachment.boqSize === null ||
    !MIME_TYPES.has(attachment.boqMimeType)
  ) {
    return new NextResponse("Not Found", { status: 404 });
  }

  const uploadDir = process.env.UPLOAD_DIR;
  if (!uploadDir || !isPrivateBoqPath(attachment.boqStoragePath)) {
    return new NextResponse("Not Found", { status: 404 });
  }

  let absolutePath: string;
  try {
    absolutePath = resolveUploadPath(uploadDir, attachment.boqStoragePath);
  } catch {
    return new NextResponse("Not Found", { status: 404 });
  }

  // เปิดไฟล์ก่อนประกอบ response เพื่อให้ไฟล์ที่หายไป (เช่นถูก retention ลบพอดี) ยังตอบ
  // 404 ได้ แทนที่จะส่ง 200 พร้อม body ขาด ๆ หลังจาก header ออกไปแล้ว
  const file = await openFile(absolutePath);
  if (!file) {
    return new NextResponse("Not Found", { status: 404 });
  }

  // ขนาดบนดิสก์ต้องตรงกับที่บันทึกไว้ตอนอัปโหลด ไฟล์ที่ถูกแก้หรือเขียนไม่จบจึงไม่หลุดออกไป
  if (file.size !== attachment.boqSize) {
    await file.close();
    return new NextResponse("Not Found", { status: 404 });
  }

  const headers = new Headers({
    "Cache-Control": "private, no-store",
    "Content-Disposition": contentDisposition(attachment.boqOriginalName),
    "Content-Length": String(attachment.boqSize),
    "Content-Type": attachment.boqMimeType,
    "X-Content-Type-Options": "nosniff",
  });

  // ไม่รองรับ Range ที่นี่โดยตั้งใจ — ไฟล์นี้เป็นการดาวน์โหลดครั้งเดียวผ่านลิงก์ในไลน์
  // ไม่ใช่สื่อที่ต้องเปิดกลางไฟล์ และการตอบไฟล์เต็มเสมอทำให้ตรวจสอบง่ายกว่า
  return new NextResponse(file.stream(), { headers });
}

/** Only paths generated by storeBoqFile are eligible; the request never supplies a path. */
function isPrivateBoqPath(storagePath: string): boolean {
  return /^quote-boq\/\d{4}\/\d{2}\/[0-9a-f-]{36}\.(pdf|xlsx)$/i.test(
    storagePath.replaceAll("\\", "/"),
  );
}

function contentDisposition(filename: string): string {
  const safe = sanitizeFilename(filename);
  const asciiFallback = safe.replace(/[^\x20-\x7e]/g, "_").replace(/["\\]/g, "_");
  const encoded = encodeURIComponent(safe).replace(/['()]/g, (character) =>
    `%${character.charCodeAt(0).toString(16)}`,
  );
  return `attachment; filename="${asciiFallback}"; filename*=UTF-8''${encoded}`;
}

function sanitizeFilename(filename: string): string {
  const safe = Array.from(
    filename
      .split(/[\\/]/)
      .pop()
      ?.normalize("NFKC")
      .replace(/[\u0000-\u001f\u007f<>:"/\\|?*]/g, "_")
      .replace(/\s+/g, " ")
      .trim() ?? "",
  )
    .slice(0, 255)
    .join("");
  return safe || "boq-download";
}
